Feat/auth
coding-kkanbu/teameet_backend pull request #196
Opened 2022-06-29 17:52 UTC by Ridealist

### Description

### 인증 부분 전체적으로 수정
1. 인증관련 settings값들 추가
2. allauth, dj-rest-auth 3rd party package 필요한 urls만 views, serializer에 구현하고 삭제
3. 위 2가지 패키지 내에 구현되어 있는 함수들 최대한 활용
- accounts/google/login 으로 인증 code값 받아 옴 -> accounts/google/login/callback으로 Redirect
- accounts/google/finish로 code값 넘기면 인증 및 중복 아이디 확인, 소셜계정 정보 가져오기 등 일괄 가능
- 기존 utils 함수들 활용안하고 dj-rest-auth에 정의된 SocialLoginView로 일괄 가져옴

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [ ] Add / update tests if necessary? **-> 추후 test코드 추가 예정**
- [x] Add new / update outdated documentation?

2022-06-30 07:31 UTC, Eunsub-thumb requested changes
일단 일부만 리뷰했어~

2022-06-30 07:31 UTC, Eunsub-thumb commented on config/settings/base.py
> +    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
google api는 리프레시 토큰을 6개월로 해놨더라구 우리도 이렇게 짧게 할 필요는 없을거야. 이렇게 하면 유저가 매일매일 로그인해야하니까

2022-06-30 07:31 UTC, Eunsub-thumb commented on config/settings/local.py
> +KAKAO_CALLBACK_URI = LOCAL_BASE_URL + "accounts/kakao/login/callback/"
이거는 local, staging, production 다 이름을 똑같이 가져가는게 좋아

2022-06-30 07:31 UTC, Eunsub-thumb commented on config/urls.py
> -    path("accounts/", include("allauth.urls")),
이거 다 지워도 Oauth 로그인 잘 작동하는거지??

2022-06-30 07:38 UTC, teacherSsamko commented on kkanbu/accounts/urls.py
> +    path("token/refresh/", get_refresh_view().as_view(), name="token_refresh"),
이거 기본적으로 있는거 아니야?? 바귄게 있어?

2022-06-30 08:42 UTC, Ridealist commented on config/settings/base.py
> +    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
아 그렇구나 refresh 토큰을 지나치게 짧게 할 필욘 없겠네. 그럼 access를 1시간으로 refresh를 1개월 정도로 수정해야겠다~

2022-06-30 08:43 UTC, Ridealist commented on config/settings/local.py
> +KAKAO_CALLBACK_URI = LOCAL_BASE_URL + "accounts/kakao/login/callback/"
아 오키 그렇네 BASE_URL이니까 말그대로... 그래야 나중에 도메인 바꿀 때 한번에 다 체크할 수 있겠다. 수정할게!

2022-06-30 08:44 UTC, Ridealist commented on config/urls.py
> -    path("accounts/", include("allauth.urls")),
응 다 작동 잘 되는거 확인했어. auth-token은 우리가 JWT 기반으로 해서 아예 안쓰고 있었고.

2022-06-30 08:45 UTC, Ridealist commented on kkanbu/accounts/urls.py
> +    path("token/refresh/", get_refresh_view().as_view(), name="token_refresh"),
응 맞어.
`path("accounts/", include("dj_rest_auth.urls")),`
이게 있을때는 기본으로 제공하는 건데, 필요한 것들을 아예 accounts app에 구현하고 나머지 3rd party app들 정리하느라 명시적으로 추가한거야~

2022-06-30 08:47 UTC, Ridealist commented
형 그리고 나도 질문 한가지 있는데,
소셜로그인 첫 시작 단계에서 `/accounts/google/login/` url이 매핑되어 있는데
이게 Swagger 문서에 반영이 안되서 어떻게 반영되게 해보려고 이것저것 해봤는데 안되더라고...ㅠ

2022-06-30 08:49 UTC, Ridealist commented
allauth 패키지에 있는 함수를 가져다 써서 그런것 같은데
이렇게 기존에 있는 패키지에서 함수를 그대로 가져다 쓸 때, extend schema를 어떻게 시킬 수 잇는거야??

2022-06-30 08:53 UTC, Ridealist commented
참고로 위 url은 GET 메소드일 때는 아래처럼 로그인 화면이 뜨고
![image](https://user-images.githubusercontent.com/89024993/176635551-b4ed1620-bbfe-4954-a5bd-228384b5a2f4.png)
![image](https://user-images.githubusercontent.com/89024993/176635669-3a100cb4-8105-4abf-887e-e640f0d27722.png)

2022-06-30 08:57 UTC, Ridealist commented
POST 메소드일 때는 소셜 계정 화면으로 이동되더라고?!
![image](https://user-images.githubusercontent.com/89024993/176636463-6c803e1b-8cca-46cd-9a84-333f2b9ff80d.png)
![image](https://user-images.githubusercontent.com/89024993/176636532-a9a4c455-a7c9-49ab-b3eb-0564e824efb9.png)

2022-07-01 01:52 UTC, teacherSsamko commented
> 형 그리고 나도 질문 한가지 있는데, 소셜로그인 첫 시작 단계에서 `/accounts/google/login/` url이 매핑되어 있는데 이게 Swagger 문서에 반영이 안되서 어떻게 반영되게 해보려고 이것저것 해봤는데 안되더라고...ㅠ

이거는 api가 아니라서 굳이 api문서에 넣을 필요는 없을것같은데? google/login 화면을 띄워주는것뿐이잖아?

2022-07-01 01:53 UTC, teacherSsamko commented
으잉 포스트로 해야 저렇게 가는거야?

2022-07-01 01:54 UTC, teacherSsamko approved these changes

2022-07-01 14:16 UTC, Ridealist commented
아 그런건가? 난 Swagger 문서에 api 말고 모든 url 정보가 다 담겨 있어야 되는줄 알았네...

2022-07-01 14:17 UTC, Ridealist commented
> 으잉 포스트로 해야 저렇게 가는거야?

응 그게 좀 특이하긴 하더라... 이유는 모르겠지만 뭐 프론트엔드 팀한테 얘기해 놓으면 될 문제이긴 한 듯.

2022-07-01 14:21 UTC, merged