Feature/random name 생성
coding-kkanbu/teameet_backend pull request #215
Opened 2022-07-23 14:04 UTC by hoetaek

### Description

- generate random name and populate it to user field if not exists

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-07-24 14:06 UTC, Ridealist commented
후딱 잘 만들었구먼ㅎㅎ

2022-07-24 14:07 UTC, Ridealist commented
코드 리뷰할건 따로 없는데,
우리 원래 기획이 유저 개인 페이지에서 주사위 모양 클릭하면 계속 새로운 random_name 생성하게 하려고 했거든.
그것만 custion_action으로 추가하면 될것 같은데?

2022-07-24 14:08 UTC, Ridealist reviewed
코드 리뷰할건 따로 없는데,
우리 원래 기획이 유저 개인 페이지에서 주사위 모양 클릭하면 계속 새로운 random_name 생성하게 하려고 했거든.
그것만 custion_action으로 추가하면 될것 같은데?

2022-07-25 02:31 UTC, hoetaek commented
> 

오키! 그 부분 추가해서 올리겠음

2022-07-25 10:27 UTC, teacherSsamko commented on kkanbu/users/tests/test_drf_views.py
> +
DB에 있는 값도 잘 바뀌었는지 한번 보자. return만 오고 DB는 그대로일 수도 있으니까
User.object.get().random_name ==

2022-07-25 10:27 UTC, teacherSsamko commented on kkanbu/users/utils.py
> +    return f"{choice(adjectives)} {choice(animals)}"
유후~ 멋져
이건 그냥 이렇게 둬도 좋지만 이렇게 데이터가 많을때는 따로 json, txt, csv같은 파일로 해당 데이터만 모아두고 불러서 쓰는게 좋아~

2022-07-25 22:13 UTC, hoetaek commented on kkanbu/users/utils.py
> +    return f"{choice(adjectives)} {choice(animals)}"
네~~ 배워가는 과정이니까 수정해서 커밋할게. 감사합니다!

2022-07-25 22:13 UTC, hoetaek commented on kkanbu/users/tests/test_drf_views.py
> +
옙!

2022-07-26 13:50 UTC, teacherSsamko requested changes

2022-07-26 13:50 UTC, teacherSsamko commented on kkanbu/users/random_name_data.json
> +{"adjectives": ["\uac00\ub0d8\ud508", "\uac00\ub294", "\uac00\uc5fe\uc740", "\uac00\ud30c\ub978", "\uac19\uc740", "\uac70\uc13c", "\uac70\uce5c", "\uac80\uc740", "\uac8c\uc73c\ub978", "\uace0\ub2ec\u
이거 왜 인코딩이 이렇게 됐어? 이러면 수정하기가 힘들겠는걸 ㅜ UTF로 인코딩해줘 
그리고 포맷팅도 해주고~ 보기좋게

2022-07-26 21:59 UTC, Ridealist reviewed
그다음, 내가 users/api/UserSeriailizer에
ramdom_name 필드를 따로 read_only_fields로 설정하지 않았는데
이것도 read_only_fieds에 추가하면 좋겠다.

generate_random_name 함수로 random_name 바꾸는거 이외에 사용자가
PUT method로 변경하는건 허용하면 안되니깐.

2022-07-26 21:59 UTC, Ridealist commented on kkanbu/users/random_name_data.json
> +{"adjectives": ["\uac00\ub0d8\ud508", "\uac00\ub294", "\uac00\uc5fe\uc740", "\uac00\ud30c\ub978", "\uac19\uc740", "\uac70\uc13c", "\uac70\uce5c", "\uac80\uc740", "\uac8c\uc73c\ub978", "\uace0\ub2ec\u
요거 은섭형이 얘기한거 수정하면 되겠다~

2022-07-26 23:42 UTC, hoetaek commented
> 요거 은섭형이 얘기한거 수정하면 되겠다~

수정해서 올린건데!

2022-07-26 23:54 UTC, hoetaek commented on kkanbu/users/random_name_data.json
> +{"adjectives": ["\uac00\ub0d8\ud508", "\uac00\ub294", "\uac00\uc5fe\uc740", "\uac00\ud30c\ub978", "\uac19\uc740", "\uac70\uc13c", "\uac70\uce5c", "\uac80\uc740", "\uac8c\uc73c\ub978", "\uace0\ub2ec\u
완료!

2022-07-27 13:00 UTC, teacherSsamko approved these changes

2022-07-28 03:21 UTC, Ridealist approved these changes

2022-07-28 03:22 UTC, Ridealist commented
수고 많았다 회택아~ㅎㅎ

2022-07-28 03:22 UTC, merged