Fix/delete nickname
coding-kkanbu/teameet_backend pull request #216
Opened 2022-07-25 02:30 UTC by hoetaek

### Description

- login serializer requests nickname but nickname field is deleted from user model

1. delete nickname from login serializer
2. delete nickname from register serializer
3. delete nickname population in social login

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-07-26 22:43 UTC, Ridealist requested changes

2022-07-26 22:43 UTC, Ridealist commented on kkanbu/accounts/serializers.py
>  class CustomRegisterSerializer(RegisterSerializer):
CustomRegisterSerializer 따로 필요 없을 것 같아.
RegisterSerializer에 email 필드가 이미 정의되 있으니 그대로 사용하면 되서.
settings에 allauth 부분에 내가 ACCOUNT_EMAIL_REQUIRED=True 조건 추가해놨어.

2022-07-26 23:56 UTC, hoetaek commented on kkanbu/accounts/serializers.py
>  class CustomRegisterSerializer(RegisterSerializer):
CustomLoginSerializer도 보면 username=None 부분만 있는데 이것도 필요해?

2022-07-27 13:08 UTC, teacherSsamko reviewed
accounts/utils랑 users/adapters는 뭔데 지운거야?

2022-07-27 13:08 UTC, teacherSsamko commented on config/settings/base.py
> -}
이건 뭔데 지우는거야? 지워도 되는거야?

2022-07-27 13:08 UTC, teacherSsamko commented on kkanbu/accounts/serializers.py
> -class CustomRegisterSerializer(RegisterSerializer):
이거 우리가 만들었던거야?

2022-07-27 13:32 UTC, hoetaek commented on kkanbu/accounts/serializers.py
> -class CustomRegisterSerializer(RegisterSerializer):
응 우리가 만들었던건데, 내가 알기로는 가입할 때 닉네임 필드까지 받으려고 customize한거야
근데 닉네임이랑 유저네임이 사실상 중복이라서 없애는 거! @Ridealist

2022-07-28 04:00 UTC, Ridealist approved these changes

2022-07-28 04:00 UTC, Ridealist commented on config/settings/base.py
> -}
응 원래 default가 dj_rest_auth RegisterSerializer로 설정되어 있는데
우리가 nickname 필드 때문에 커스터마이징 했던거거든.
근데 nickname 필드를 없에서 username를 nickname 필드처럼 사용하기로 해서, 커스터마이징 할 필요가 없어졌어~

2022-07-28 04:00 UTC, Ridealist commented on kkanbu/accounts/serializers.py
> -class CustomRegisterSerializer(RegisterSerializer):
맞습니당~!

2022-07-28 04:41 UTC, Ridealist commented on kkanbu/accounts/serializers.py
>  class CustomRegisterSerializer(RegisterSerializer):
응 CustomLoginSerializer는 남겨 놓는 걸로~

2022-07-28 09:34 UTC, hoetaek commented on config/settings/base.py
> -}
conversation resolve해도 될까요?

2022-07-30 10:25 UTC, merged