Feat/auth/neis email
coding-kkanbu/teameet_backend pull request #252
Opened 2022-08-04 09:47 UTC by hoetaek

### Description

- verify user by sending email to neis email address
- constraint for user model to exclude duplicate neis email address
- redirection to frontend once verified

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-08-05 17:50 UTC, Ridealist requested changes
진짜 고생해서 만든 흔적이 보인다! 수고 많았어~
나는 최대한 있는 코드 가져다 쓰는 편인데 너는 로직을 짜서 만드는게 대단하네 진짜. 많이 배웠다!

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/views.py
> +    permission_classes = [IsAuthenticated]
이건 settings/base.py에 DRF 부분에 DEFAULT_PERMISSION_CLASSES 설정해놔서 따로 명시하지 않아도 될것 같아~

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
나도 쭉 봤는데 JWT의 AccessToken을 사용하는 것보다 Django built-in PasswordResetTokenGenerator을 사용하면 어떨가 해서. 패스워드 초기화에 사용되는 거지만 커스터마이징 해서 쓰는거지.
그 이유는
1. JWT는 길이가 너무 길어서 이메일에 띄워질 때 사용성이 불편
2. 위에를 사용하면 expire date를 설정해 token에 포함시킬 수 있음 
   -> (PASSWORD_RESET_TIMEOUT) 파라미터인데 오버라이딩 해서 이름을 바꿔서 쓰면 될듯
3. 한번만 사용될 수 있음 한번 쓰인 이후에는 재발급 받아야만 가능
    -> 나중에 여러번 발급받은 유저 블랙리스트에 추가도 가능할 것 같고

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
https://medium.com/swlh/email-verified-user-registration-and-password-reset-in-django-ffb9b30939a8

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
https://pylessons.com/django-email-confirm

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
참고할만한 링크 남겨놓을게~

2022-08-05 17:50 UTC, Ridealist commented on kkanbu/accounts/tests/test_views.py
> +def reverse_querystring(
요거는 test code 맨 앞부분에 정의하는게 어떨까?
베타테스트나 배포 이후에도 밑에 계속 추가로 test 코드 작성할 수 있으니. 구분되기 쉽게~

2022-08-06 05:26 UTC, hoetaek commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
오키! 길이 긴 거는 html a tag 사용하면 문제 없긴 하고 expire date도 settings에 있는 변수 활용하도록 설정 되어 있더라고. 근데 한번 사용만 가능하도록 하는 거라던가 보통 PasswordResetTokenGenerator 사용하니까 이걸로 할게

2022-08-06 05:27 UTC, hoetaek commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
근데 PASSWORD_RESET_TIMEOUT 변수를 설정해두면 실제로 password reset할 때에도 그 timeout이 적용될거야. 원하는 expire 시간 있어?

2022-08-06 06:06 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
그래서 나는
django.contrib.auth.token에서
check_token 부분을 오버라이딩하면 어떨까 생각했어.
변수명을 변경하는거지
NEIS_VERIFY_TIMEOUT 이런식으로
이게 들어있는 if문만 커스터마이징 할 순 없으려나 나머진 super() 하고?!
패스워드는 디폴트 1일이라 그것보다 짧게 잡으면 if문 추가해도 문제는 없는거잖아?

2022-08-06 06:07 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
![Screenshot_20220806-150246_Samsung Internet.jpg](https://user-images.githubusercontent.com/89024993/183236659-c2c5efab-a1c5-47b5-9d69-0c258b6689cb.jpg)

2022-08-07 08:15 UTC, hoetaek commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
그니까.. 음 password timeout을 바꾸고 싶은거지? timeout을 얼마로 설정했으면 좋겠어?

2022-08-07 10:01 UTC, Ridealist commented on kkanbu/accounts/views.py
> +        token = AccessToken.for_user(request.user)
10분이면 충분하지 않을까?

2022-08-09 10:16 UTC, Ridealist approved these changes
고생 많았어 회택아 굳굳ㅎㅎ

2022-08-09 10:18 UTC, merged