Feat/auth
coding-kkanbu/teameet_backend pull request #26
Opened 2022-01-16 07:02 UTC by hoetaek

### Description
social login 구글이랑 카카오 추가했습니다
accounts라는 앱을 만들었고 env 활용해서 client id 등 받아오도록 했습니다

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-01-16 07:15 UTC, Ridealist commented
CI / pytest (pull_request) 이거 실패했다고 뜨는데 한번 확인해보세요!

2022-01-16 07:18 UTC, teacherSsamko commented
PR 내용 수정 조금 했어요~ @hoetaek

2022-01-16 07:24 UTC, teacherSsamko requested changes
실제 프로젝트 개발관련 코드는 다 kkanbu 폴더 하위에 넣을게요. accounts앱도 kkanbu/accounts로 이동해주세요~

2022-01-16 07:24 UTC, teacherSsamko commented on accounts/apps.py
> +    name = "accounts"
`name = "kkanbu.accounts"`로 변경해주셔야해요~

2022-01-16 07:24 UTC, teacherSsamko commented on accounts/views.py
> +GOOGLE_CALLBACK_URI = env("GOOGLE_CALLBACK_URI")
callback uri는 환경변수로 안하는게 좋을것같아요 FE에서도 확인하기 쉬워야하니까요~

2022-01-16 07:24 UTC, teacherSsamko commented on accounts/views.py
> +    print(code, state)
배포 전에 print는 전부 지울게요~ 개발 동안에만 사용하구요~ 미리 인지하도록 말씀만 드리는거니 이건 수정하지 않으셔도 돼요~

2022-01-16 07:24 UTC, teacherSsamko commented on accounts/views.py
> +        # return JsonResponse(accept_json)
이건 왜 남겨 놓은건가요?

2022-01-16 07:24 UTC, teacherSsamko commented on config/settings/base.py
> +    "accounts"
kkanbu.accounts

2022-01-16 08:41 UTC, Ridealist commented on accounts/views.py
> +        # return JsonResponse(accept_json)
회원가입 과정에서 오류 발생하는 경우 에러메세지 리턴하는 코드 같은데 설정해놓는게 낫지 않을까요?
이거대로 돌리니까 오류가 발생한건가?

2022-01-16 09:01 UTC, Eunsub-dev commented on accounts/views.py
> +        # return JsonResponse(accept_json)
오류는 requirements에서 발생한거같구요. 사용하지 않을 코드라면 지워주시고 이후에 사용할 코드라면 언제 사용할건지 혹은 왜 주석처리했는지 남겨주어야 나중에 주석을 해제하거나 삭제할 결정하기가 쉬워요

2022-01-16 09:03 UTC, Eunsub-dev requested changes

2022-01-16 09:03 UTC, Eunsub-dev commented on requirements/base.txt
> +dj-rest-auth==2.2.2[with_social] # https://github.com/iMerica/dj-rest-auth
With social 이게 패키지에 포함된 이름인가요?그렇다면 dj-rest-auth[with_social]==2.2.2 이렇게 해주시고 그냥 설명이면 주석으로 남겨주세요. 여기서 test 실패가 됐네요

2022-01-16 09:06 UTC, hoetaek commented on requirements/base.txt
> +dj-rest-auth==2.2.2[with_social] # https://github.com/iMerica/dj-rest-auth
네~ 꼼꼼하게 하나하나 리뷰해주셔서 정말 감사드려요. 이런 걸 정말 많이 기다려왔어요ㅜ 하나하나 잘 반영하겠습니다

2022-01-16 09:07 UTC, hoetaek commented on accounts/apps.py
> +    name = "accounts"
옙~

2022-01-16 09:08 UTC, hoetaek commented on accounts/views.py
> +        # return JsonResponse(accept_json)
에러가 나서 주석 처리하고 다른 방법으로 구현헤봤어요. 앞으로 필요 없는 코드일 거 같아서 지우겠습니다~

2022-01-16 12:02 UTC, Ridealist approved these changes, later dismissed
고생 많았어요~ 굳굳!

2022-01-16 13:56 UTC, teacherSsamko requested changes

2022-01-16 13:56 UTC, teacherSsamko commented on config/urls.py
> +    # path("accounts/", include("allauth.urls")),
쌤 pytest 결과 보면
```shell
=================================== FAILURES ===================================
__________________ TestUserDetailView.test_not_authenticated ___________________

self = <kkanbu.users.tests.test_views.TestUserDetailView object at 0x7fab9145efa0>
user = <User: vickiesantiago>
rf = <django.test.client.RequestFactory object at 0x7fab91475640>

    def test_not_authenticated(self, user: User, rf: RequestFactory):
        request = rf.get("/fake-url/")
        request.user = AnonymousUser()
    
>       response = user_detail_view(request, username=user.username)

kkanbu/users/tests/test_views.py:93: 
```
```shell
>       raise NoReverseMatch(msg)
E       django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
```
이렇게 에러가 뜨는데 보니까 url을 건드린 부분이 여기밖에 없는걸로 봐서 account_login이라는 url이 allauth.urls에 있는것같아요.
당장은 쓰지 않더라도, 일단 테스트 통과를 위해서 주석해제 하고, 해당 내용은 issue로 남기고 이후에 해결하는 걸로 해요
주석해제 한 다음에 제일 밑으로 넣어두면 다른 경로랑 문제가 생기지는 않을거에요.
```python
urlpattern = [
  ...,
  path("accounts/", include("kkanbu.accounts.urls")),
  path("accounts/", include("allauth.urls")), # 리스트 가장 마지막 요소로 이동
]
```
이렇게요

2022-01-16 14:29 UTC, teacherSsamko requested changes

2022-01-16 14:29 UTC, teacherSsamko commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
쌤 상수들은 다 settings에서 관리할게요. 그래야 관리가 용이해요. BASE_URL같은 경우도 환경마다 다른거니까요.

2022-01-16 14:48 UTC, hoetaek commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
옙 감사합니다~

2022-01-16 14:49 UTC, hoetaek commented on config/urls.py
> +    # path("accounts/", include("allauth.urls")),
아 겹치는 것 때문에 걱정했는데 한방에 해결됐네요 감사합니다~

2022-01-16 15:08 UTC, hoetaek commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
AttributeError: 'Settings' object has no attribute 'GOOGLE_CLIENT_ID'

settings에 넣어서 했는데 또 pytest 에러가 나네요. 시간 늦어서 내일 해결하겠습니다ㅜ

2022-01-16 23:41 UTC, teacherSsamko commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
아 이게 아마 test용은 따로 test.py에 세팅해줘야할거같아요.

2022-01-16 23:42 UTC, teacherSsamko commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
config/settings/test.py

2022-01-17 09:33 UTC, hoetaek commented on kkanbu/accounts/views.py
> +KAKAO_CALLBACK_URI = "http://localhost:8000/accounts/kakao/callback/"
네 알겠습니다

2022-01-17 11:11 UTC, teacherSsamko approved these changes
고생하셨어요! 👍

2022-01-17 11:11 UTC, merged