Feat/board/post update
coding-kkanbu/teameet_backend pull request #43
Opened 2022-01-25 15:25 UTC by Ridealist

### Description
- models: Post/category field -> ForiegnKey 변경
- serializer: MainListSerializer(메인화면용) 추가
- views: PostViewsets 주석 처리
         MainListView 추가

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-01-26 03:31 UTC, teacherSsamko commented on CHANGELOG.md
> +### Modify Board App
이건 그냥 Board 라고만 써주고 아래에 변경, 추가 등 내용써주면 될 것 같아~

2022-01-26 03:31 UTC, teacherSsamko commented on kkanbu/board/serializers.py
> +    comment_cnt = SerializerMethodField()
개수같은건 cnt보다는 comment_n 으로 많이 사용하니까 우리도 그렇게 하는걸로?

2022-01-26 03:31 UTC, teacherSsamko commented on kkanbu/board/serializers.py
> +class MainListSerializer(ModelSerializer):
MainList라는게 무슨 의미야? board list인데 main화면에서 category별로 보여주는 list??

2022-01-26 03:31 UTC, teacherSsamko commented on kkanbu/users/migrations/0002_alter_user_nickname.py
> +        ),
user모델에 변경된게 없는데 왜 migrations파일이 새로 생겼지?

2022-01-26 07:59 UTC, teacherSsamko commented
commit 메세지 신경쓰기ㅜㅜㅜ 푸시하기전에 pre-commit해서 무의미한 commit 발생하지 않게 하기

2022-01-26 08:38 UTC, Ridealist commented
> commit 메세지 신경쓰기ㅜㅜㅜ 푸시하기전에 pre-commit해서 무의미한 commit 발생하지 않게 하기

헐... github 상에서 edit 창 열어서 수정하다보니 commit 메세지 rule 지키는 게 또 안됐네....ㅠㅠㅠㅠ
더 꼼꼼하게 작업해야 겠다 앞으로... 송구하옵니다...ㅠㅠ

형은 보통 코드 리뷰 다 된거 vscode에서 수정해서 다시 PR 날리는 편이야??
github에서 수정하는게 편하다 생각해서 썼는데, pre-commit 돌리기도 어렵고 문제점이 많네 생각보다...ㅠㅠ

2022-01-26 08:44 UTC, Ridealist commented
일단 6시에 크로스핏 갔다와서 바로 수정해놓을게.. 실수 투성이네...ㅠㅠ
수정 후 Re-request review 보내겠습니다....

2022-01-27 03:22 UTC, teacherSsamko reviewed
Migration파일관련해서는 아직 해결중인거지??

2022-01-27 03:22 UTC, teacherSsamko commented on kkanbu/board/serializers.py
> +#         fields = "__all__"
이건 삭제하는게 좋을듯 이후에 주석해제 할 일은 없을것같아

2022-01-27 03:22 UTC, teacherSsamko commented on kkanbu/board/urls.py
> +    url(r"^$", BoardListView.as_view(), name="main_board"),
`board-list` 이게 drf convention이라 이렇게 가는게 통일성있을거같아~

2022-01-27 03:23 UTC, teacherSsamko commented
> > commit 메세지 신경쓰기ㅜㅜㅜ 푸시하기전에 pre-commit해서 무의미한 commit 발생하지 않게 하기
> 
> 헐... github 상에서 edit 창 열어서 수정하다보니 commit 메세지 rule 지키는 게 또 안됐네....ㅠㅠㅠㅠ 더 꼼꼼하게 작업해야 겠다 앞으로... 송구하옵니다...ㅠㅠ
> 
> 형은 보통 코드 리뷰 다 된거 vscode에서 수정해서 다시 PR 날리는 편이야?? github에서 수정하는게 편하다 생각해서 썼는데, pre-commit 돌리기도 어렵고 문제점이 많네 생각보다...ㅠㅠ

저번에 말했듯이 github에서 직접 수정한거 그때 처음해봤어 ㅋㅋ 보통은 다 IDE에서 작업하지 그래야 formatter도 작동하고, 테스트코드도 돌려볼 수 있으니까

2022-01-27 07:07 UTC, Ridealist commented
> Migration파일관련해서는 아직 해결중인거지??

넵 새로운 폴더에 git clone해서 다시 실행해본 결과 똑같이 해당 파일 생성됨 확인했습니다~
즉, 다른 컴퓨터에서 git pull해서 실행시키면 어차피 해당 파일 똑같이 생성될테니 삭제하거나 추가 수정 필요 없어 보여!

2022-01-27 07:09 UTC, Ridealist commented
> 저번에 말했듯이 github에서 직접 수정한거 그때 처음해봤어 ㅋㅋ 보통은 다 IDE에서 작업하지 그래야 formatter도 작동하고, 테스트코드도 돌려볼 수 있으니까

나도 그냥 IDE에서 작업하는 걸로 아예 습관화 해야겠다... 조금 편한거 쓰다가 실수하느나 안전하게 가는게 훨씬 좋은듯!

2022-01-27 07:20 UTC, Ridealist commented
수정사항 얘기해준거 다시 반영해 commit 추가 했습니다~!
꼼꼼한 코드 리뷰 고마워 형...ㅎㅎ
현직자의 코드 짜는 자세를 경험해보는 값진 경험이다 진짜...!

2022-01-27 11:49 UTC, hoetaek commented on kkanbu/board/urls.py
> +app_name = "post"
app_name이 post 대신에 board가 낫지 않을까요?

2022-01-27 14:23 UTC, teacherSsamko requested changes

2022-01-27 14:23 UTC, teacherSsamko commented on kkanbu/board/urls.py
> +app_name = "post"
그러네 저거 못봤는데 app_name은 "board"가 되어야겠다

2022-01-27 14:26 UTC, teacherSsamko commented
> 넵 새로운 폴더에 git clone해서 다시 실행해본 결과 똑같이 해당 파일 생성됨 확인했습니다~ 즉, 다른 컴퓨터에서 git pull해서 실행시키면 어차피 해당 파일 똑같이 생성될테니 삭제하거나 추가 수정 필요 없어 보여!

그렇긴한데 이번 PR이 board에 관련된건데 user migration이 들어가 있어서 ㅋ 이게 별거 아니긴한데 나중에 이게 왜 이렇게 되어있지? 하고 커밋히스토리 찾아볼때 이렇게 되어있으면 찾기가 좀 힘들어지거든 
이번에는 그냥 넘어가는걸로 하고 다음부터는 makemigration kkanbu.board 이렇게 앱 지정해서 makemigration하자 ㅋㅋ

혹시 이번에도 수정하고 싶으면 `git rebase -i 7aeb3e0674f` 이걸로 해서 해당 커밋 drop할 수 있긴해 ㅋㅋ

2022-01-28 03:23 UTC, Ridealist commented
그래도 완벽을 기하기 위해 user migrations 커밋도 drop 했습니다~!
형이 말해준 대로 따로 앱 지정해서 makemigrations 명령 처리할게. 앱별로 makemigrations 가능한 줄은 또 몰랐네!

2022-01-28 04:27 UTC, Ridealist commented
migrations 파일 commit에서 지웠더니 pytest에 또 문제가 생겨서 엄청 해맸네요....
어찌저찌 완료 했습니다 그래도ㅠㅠ
너무 지저분 하네요 PR창이 열었다 닫았다 아주 쌩 난리를...

2022-01-28 09:04 UTC, hoetaek approved these changes

2022-01-28 14:08 UTC, teacherSsamko approved these changes
굿굿 👍 초반에 좀 고생하다보면 나중엔 금방금방 될거야!

2022-01-28 14:08 UTC, merged