Feat/board/board
coding-kkanbu/teameet_backend pull request #46
Opened 2022-01-29 02:42 UTC by Ridealist

### Description

- board 앱 수정사항
1. create serializer, view, url 추가
2. view에 따른 permission 권한 설정
- BoardList -> Allowany
- PostCreate -> Authenticated

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-01-29 06:24 UTC, teacherSsamko requested changes

2022-01-29 06:24 UTC, teacherSsamko commented on kkanbu/board/urls.py
> +    url(r"^create/$", PostCreateView.as_view(), name="create"),
DRF나 보통 url convention은 list와 동일한 주소로 post method일때 create되게 하는거거든
그래서 BoardListView를 BoardView로 바꾸고, 거기에 CreateListView를 상속해서 create도 같은 url에서 하게 하는게 좋을거같아
지금처럼 하면 클래스 뷰를 사용하는 장점이 없어지고 그냥 함수형 뷰 사용하는 것처럼 되어버려서

2022-01-29 08:33 UTC, Ridealist commented on kkanbu/board/urls.py
> +    url(r"^create/$", PostCreateView.as_view(), name="create"),
아 형이 얘기한거 해결하면서 CBV가 뭔지 좀 더 확실히 알게됐다!
그렇네 CBV라는게 사실 여러개의 FBV를 클래스화 시키는 거니까.
메소드 별로 다른 뷰를 사용하는건 낭비적인 거였구나...

2022-01-29 08:43 UTC, Ridealist commented on kkanbu/board/views.py
> +    # @api_view(['GET'])
형 이건 내 질문인데,
CBV로 하니까 permission_classes를 메소드별로 설정하는게 잘 안되네ㅠ
DRF 공식 문서에 FBV에서 위와 같은 방식으로 구현했길래 적용해봤는데 작동이 안되더라구...
이건 질문하려고 일부로 지우지 않고 주석처리 해놨어!

2022-01-29 08:44 UTC, Ridealist commented on kkanbu/board/views.py
> +    # @permission_classes([Allowany])
형 이건 내 질문인데,
CBV로 하니까 permission_classes를 메소드별로 설정하는게 잘 안되네ㅠ
DRF 공식 문서에 FBV에서 위와 같은 방식으로 구현했길래 적용해봤는데 작동이 안되더라구...
이건 질문하려고 일부로 지우지 않고 주석처리 해놨어!

2022-01-30 01:59 UTC, Ridealist commented on kkanbu/board/views.py
> +    # @permission_classes([Allowany])
이거 해결됐다! 클래스내 메소드별로 설정하는 걸 CBV내에서 하는게 아니고,
permission 함수에서 method 별로 조절하면 되는거였네~
IsAuthenticatedOrReadOnly 함수만 적용하면 간단히 해결되는 것을...
여튼 굳!
@teacherSsamko

2022-02-01 14:34 UTC, teacherSsamko requested changes
👍

2022-02-01 14:34 UTC, teacherSsamko commented on kkanbu/board/views.py
> +        serializer.save(writer=user)
이런건 굳이 두 줄로 분리하지 않아도 될거같아 `writer=self.request.user` 이렇게 해도 저게 user를 뜻하는게 명확하니까~

2022-02-02 02:34 UTC, Ridealist commented on kkanbu/board/views.py
> +        serializer.save(writer=user)
오키! 최대한 짧고 간결한 코드 구현!

2022-02-04 01:11 UTC, teacherSsamko approved these changes

2022-02-04 01:11 UTC, merged