Feat/auth flow
coding-kkanbu/teameet_backend pull request #51
Opened 2022-02-01 11:15 UTC by hoetaek

### Description
- 소셜 로그인 수정사항

1. 구글 및 카카오 client id와 secret key를 데이터베이스에서 호출
2. 회원가입 과정에서 사용자 닉네임 입력 받음
3. accounts 앱에서 view에 사용되는 함수들은 utils.py 파일로 분리
4. 회원가입 및 로그인 하기 전에 사용자의 계정이 존재하는지 확인하는 기능 추가

- 소셜 로그인 수정 이유

1. 데이터베이스에 저장되어 있는 client id를 환경 변수 설정 불필요
2. 티밋의 use case에는 닉네임을 회원가입 과정에서 설정해야 함

### Checklist - did you ...

- [v] Add a CHANGELOG entry if necessary?
- [v] Add / update tests if necessary?
- [v] Add new / update outdated documentation?

2022-02-01 11:31 UTC, hoetaek commented
user 관련 test가 모두 fail하는데 SocialApp이 존재하지 않는다는 거 같아요. 왜 오류가 생기는지 모르겠어서 좀 더 연구해보겠습니다

2022-02-01 13:20 UTC, hoetaek commented
SocialApp.objects.get(provider="google").client_id -> 이것 때문인 것 확인
db에서 client id를 받아오기 위한 코드인데 어떻게 해결할지 알아보는 중

2022-02-01 13:23 UTC, hoetaek commented
함수 안에서 client id 및 secret key 읽어들이니 pytest 통과 확인

2022-02-01 13:24 UTC, hoetaek commented
앞으로는 push하기 전에 pytest 하는 습관 들이도록 하겠습니다

2022-02-01 14:42 UTC, teacherSsamko commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
이게 어떻게 DB에 들어가 있어?? 누가 언제 DB에 넣는거야??

2022-02-02 02:32 UTC, Ridealist commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
이건 admin 사이트에서 소셜계정 등록하면서 client_id 랑 secret_key(카카오는 없음) 입력한 값을 바탕으로 받아오는 것 같아.

2022-02-02 02:34 UTC, Ridealist commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
관리자가 미리 등록하는 값들! 지금 밖이라, 이따 내가 admin 사이트 캡쳐창 찍어서 보낼게.

2022-02-02 13:25 UTC, hoetaek commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
응 관리자가 admin에서 입력을 해주어야 해

2022-02-02 13:26 UTC, hoetaek commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
allauth에서도 admin에서 입력하는 방식으로 작동해

2022-02-05 05:44 UTC, Ridealist requested changes

2022-02-05 05:44 UTC, Ridealist commented on kkanbu/accounts/views.py
>  import environ
이건 안쓰이니까 빼도 되겠다

2022-02-05 05:44 UTC, Ridealist commented on kkanbu/accounts/views.py
>  env = environ.Env()
이 부분도 필요 없고 그럼

2022-02-05 05:44 UTC, Ridealist commented on kkanbu/accounts/utils.py
> +        social_user = SocialAccount.objects.get(user=user)
내가 local에서 실행할 때, SocialAccount 모델 instance가 아예 존재하지 않아서
오류나면서 멈출때가 있더라고.
SocialAccount로 가입한 사용자가 한명도 없는 상태에서,
일반 account로 가입한 사람이 동일한 email로 소셜 로그인을 시도할 때
user.DoesNotExist는 지나가지만 SocialAccount.DoesNotExist로 에러가 나오는 거지.

2022-02-05 05:44 UTC, Ridealist commented on kkanbu/accounts/utils.py
> +
`except SocialAccount.DoesNotExist:`
이거에 대한 코드도 추가하는게 어떨까 싶음
위에 `social_uer is None:` 부분과 동일하게 처리하면 될듯

2022-02-05 05:44 UTC, Ridealist commented on kkanbu/accounts/views.py
> +    GOOGLE_CLIENT_SECRET = SocialApp.objects.get(provider="google").secret
![image](https://user-images.githubusercontent.com/89024993/152630335-f6e39fe4-944b-48c4-a0b6-ebdba8b5f460.png)

2022-02-13 06:32 UTC, teacherSsamko approved these changes

2022-02-14 13:58 UTC, teacherSsamko commented
@Ridealist 리뷰~

2022-02-14 14:58 UTC, Ridealist approved these changes
다시 보니 adapters.py에 `populate_user` override한 거 인상 깊네~
회원가입시 받아오는 값을 adapter 이용해서 커스터마이징 하는거 배웠다!

2022-02-15 15:27 UTC, merged