Feat/blame
coding-kkanbu/teameet_backend pull request #58
Opened 2022-02-04 15:24 UTC by hoetaek

### Description

- viewset for post and comment blame
- create, list, retrieve, delete method added
- updating seems unnecessary
- validator for only one blame allowed on one post by a user

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-02-05 07:57 UTC, teacherSsamko requested changes

2022-02-05 07:57 UTC, teacherSsamko commented on kkanbu/operation/serializers.py
> +        ]
model에도 unique constraint를 넣어주는게 좋겠다

2022-02-05 07:57 UTC, teacherSsamko commented on kkanbu/operation/views.py
> +    GenericViewSet,
modelViewSet을 상속받는게 낫지 않아??

2022-02-05 15:25 UTC, hoetaek commented on kkanbu/operation/views.py
> +    GenericViewSet,
이거 어떻게 생각하는지 궁금했어. updatemodelmixin은 사용하지 않을 거라서 나머지만 사용하는 걸로 했는데
1. blame에 대해서 update 사용할 것인지?
2. update 사용하지 않더라도 ModelViewSet 사용하는지

2022-02-05 15:25 UTC, hoetaek commented on kkanbu/operation/serializers.py
> +        ]
넣어보겠습니다!

2022-02-06 04:08 UTC, teacherSsamko commented on kkanbu/operation/views.py
> +    GenericViewSet,
음 안쓰더라도 이럴땐 그냥 하나 상속해서 쓰는게 어떨까? 아니면 update빼고 저것들만 상속하는 abstract class하나 만들어서 그걸 상속받던지? 안쓰는 함수는 상속받고
```python
def update(self):
  pass
```
이런식으로 해주기도 해

2022-02-06 09:14 UTC, Ridealist commented on kkanbu/operation/views.py
> +    GenericViewSet,
오 삼코형 조언은 나도 배웠다. 필요없는 method는 pass 처리하면 되는구먼. 근데 저것들만 상속하는 abstract class를 하나 만들어서 그걸 상속받는건 결국 회택이 구현방법을 반복하는거 아닌가?? @teacherSsamko

2022-02-06 09:38 UTC, Ridealist requested changes

2022-02-06 09:38 UTC, Ridealist commented on kkanbu/operation/views.py
> +    GenericViewSet,
일단 신고 기능에 update는 필요 없어보이고, 사실 delete 기능이나 retrieve 기능도 필요 없지 않을까??
유저 입장에서는 신고할 대상을 신중히 골라서 신고하는 create 기능만 사용하는거지,
신고한 내역을 볼 필요는 없고(retrieve) / 신고를 신중하게 하라는 의미에서 삭제 기능 지원하지 않고.(destroy)
어떻게 생각하시나요~?
@hoetaek

2022-02-06 09:38 UTC, Ridealist commented on kkanbu/operation/views.py
> +    GenericViewSet,
![image](https://user-images.githubusercontent.com/89024993/152674563-3751c871-0e48-4841-8bb0-c1a4fc32c8b5.png)

인디스쿨 reperence 참고용

2022-02-06 09:38 UTC, Ridealist commented on kkanbu/operation/serializers.py
> +        ]
이거는 회택이가 한 방법대로 serializer에만 validator 적용해야 되는거 아닐까??
예를 들어 model에도 적용된다고 하면은
`PostBlame` 테이블에 유저는 유일하게 하나 존재하고, post도 유일하게 하나 존재해야 하는건데,
한 user가 다양한 post에 신고할 수도 있고
한 post에 여러 user가 신고할 수도 있는거니까,
model field에 대한 unique constraint는 안되지 않나 생각해봤어!

회택이가 구현한건 내가 DRF 공식 사이트에서 이해하기로는
저 두개 쌍이 unique한지 보는거 같더라고.
한 user가 같은 게시물에 두번 신고할 수 없게 하려는 우리 구현방향과 동일한거지!

맞게 이해했는지 나도 좀 헷갈리니 피드백 부탁드립니다.ㅎㅎㅎ
@hoetaek @teacherSsamko

2022-02-06 09:38 UTC, Ridealist commented on kkanbu/operation/serializers.py
> +        ]
[https://www.django-rest-framework.org/api-guide/validators/#uniquetogethervalidator](https://www.django-rest-framework.org/api-guide/validators/#uniquetogethervalidator)

2022-02-08 13:33 UTC, teacherSsamko commented on kkanbu/operation/serializers.py
> +        ]
한 user가 다양한 post에 신고가능
한 post에 여러 user가 신고가능 

하지만, 한 user가 한 post에는 한번만 신고가능.

이 경우에는 user, post로 unique constraint를 걸어주는게 좋아 serializer로는 완벽하게 되지 않으니까(api를 통한 제어만 가능) model단에서도 적용해주는게 확실하지

2022-02-13 06:15 UTC, teacherSsamko reviewed
makemigrations 후 migration 파일도 추가해줘~

2022-02-13 06:31 UTC, teacherSsamko approved these changes

2022-02-14 01:06 UTC, Ridealist approved these changes

2022-02-14 13:56 UTC, merged