Feat/board/post
coding-kkanbu/teameet_backend pull request #59
Opened 2022-02-06 12:21 UTC by Ridealist

### Description

- Category model field 수정
1. desription 필드 삭제
2. slug 필드 추가 -> TopicView url kwargs로 활용
- PostView, TopicView 추가
1. PostView = 개별 게시물 보여주는 detail view
2. TopicView = 토픽(카테고리)별 게시물 보여주는 list view

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-02-08 13:44 UTC, teacherSsamko reviewed
공부많이 했겠다!! 고생했어!! 👍

2022-02-08 13:44 UTC, teacherSsamko commented on CHANGELOG.md
> +  - PostSerializer, BoardListSerializer, PostCreateSerializer
이렇게 한줄로 쓰면 각각 serializer 업데이트 상황은 반영하기 힘들텐데~

2022-02-08 13:44 UTC, teacherSsamko commented on kkanbu/board/views.py
> +        queryset = Category.objects.order_by("pk")
이거 이렇게 해도 되는거야? `Category.objects.all()` 하면 default가 이거 아니야?? order_by("pk") 그리고 order_by써주려면 `all().order_by("pk")` 나 `filter().order_by("pk")` 이렇게 해야하지 않아?

2022-02-08 13:44 UTC, teacherSsamko commented on kkanbu/board/views.py
> +        queryset = Category.objects.order_by("pk")
`python manage.py shell_plus`로 한번 테스트해봤어?

2022-02-08 13:44 UTC, teacherSsamko commented on kkanbu/board/views.py
> +        return Response(serializer.data)
여기는 왜 override한거야??

2022-02-12 10:37 UTC, Ridealist commented on CHANGELOG.md
> +  - PostSerializer, BoardListSerializer, PostCreateSerializer
그렇긴 하네. 수정사항이 더 생길 수 있으니 원래대로 하는게 낫겠다.

2022-02-12 10:48 UTC, Ridealist commented on kkanbu/board/views.py
> +        queryset = Category.objects.order_by("pk")
응 일단 `queryset = Category.objects.order_by("pk")` 해도 문제 없이 잘 실행돼~

2022-02-12 10:48 UTC, Ridealist commented on kkanbu/board/views.py
> +        queryset = Category.objects.order_by("pk")
![image](https://user-images.githubusercontent.com/89024993/153708283-a303e2cb-b25e-4a61-8aea-35574f7cd06b.png)

2022-02-12 10:52 UTC, Ridealist commented on kkanbu/board/views.py
> +        queryset = Category.objects.order_by("pk")
내 DB 기준으로는 왜인지 모르겠는데 건강,헬스 카테고리가 맨 먼저 나오더라고.
그래서 두근두근 후기가 먼저 나오게 하려고 pk 기준으로 다시 정렬한거야~

2022-02-12 10:56 UTC, Ridealist commented on kkanbu/board/views.py
> +        return Response(serializer.data)
이건 PostView 클래스의 기본 serializer_class 가 `PostCreateSerializer`로 돼어 있어서
게시물 디테일을 보여주는 retrieve 함수에는 `PostSerializer`를 별도로 지정하려고 override 했어.
`PostCreateSerializer`는 게시물 만들기 용(카테고리, 제목, 내용, 태그 필드만),
`PostSerializer`는 게시물 조회용(더 많은 정보 담고 있음)

2022-02-13 06:39 UTC, teacherSsamko commented on kkanbu/board/views.py
> +        return Response(serializer.data)
https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields
postSerializer를 하나만 사용해서 조회용은 readonly로 만들면될거야~!

2022-02-14 13:57 UTC, teacherSsamko requested changes
conflict 해결해주세요~

2022-02-15 15:35 UTC, teacherSsamko commented on kkanbu/board/serializers.py
> +            "comment_n",
이거랑 postlike_n도 readonly fields로 가야겠다~

2022-02-15 15:35 UTC, teacherSsamko commented on kkanbu/board/views.py
> +            return Response(serializer.data)
이건 response로 뭘 주는거야? 그냥 성공실패여부만 주면 되지 않을까? `Response(status=status.HTTP_201_...)` 이렇게

2022-02-15 15:35 UTC, teacherSsamko commented on kkanbu/board/views.py
> +            return Response(serializer.data)
여기는 204가 되겠지?

2022-02-15 16:32 UTC, hoetaek commented on kkanbu/board/views.py
> +            return Response(serializer.data)
감사합니다! status에 no content랑 created 이런 식으로 사용하는 줄 몰랐네

2022-02-16 09:12 UTC, teacherSsamko approved these changes

2022-02-16 09:13 UTC, teacherSsamko commented on kkanbu/board/views.py
> +            return Response(serializer.data)
이거 닫아놓으면 내가 다시 펼쳐봐야해서~ 연 사람이 최종 해결됐는지 확인하고 닫는걸로하자~

2022-02-16 09:13 UTC, merged

2022-02-18 00:46 UTC, hoetaek commented on kkanbu/board/views.py
> +            return Response(serializer.data)
넵ㅎㅎ