Feat/notification
coding-kkanbu/teameet_backend pull request #72
Opened 2022-02-18 13:15 UTC by Ridealist

### Description
1. Notification 앱 생성
- Notification Model 추가
- serializer, viewset 추가
- router에 등록

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-02-18 13:48 UTC, teacherSsamko requested changes

2022-02-18 13:48 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
```python
class Noptification():
  class Type(models.TextChoices):
    comment = "comment"
    postlike = "PostLike"
  
  notification_type = models.CharField(max_length=20, choices=Type.choices)
```
이런식으로 쓰는 방법도 있어~

2022-02-18 13:48 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
알람을 유저와 유저간에 줄 수도 있는거야? 이 속성은 어떤 속성이야?

2022-02-18 13:48 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
https://docs.djangoproject.com/ko/4.0/ref/models/fields/#choices

2022-02-18 13:48 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    is_read = models.BooleanField(default=False)
extra_id는 뭐 할때 필요해?

2022-02-18 13:48 UTC, teacherSsamko commented on kkanbu/notification/views.py
> +class NotificationViewSet(ListModelMixin, GenericViewSet):
python mro랑 관련해서 보통 Mixin을 나중에 쓰니까 여기선 큰 문제가 없더라도, ViewSet을 먼저 상속해주자!

2022-02-19 00:53 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
헐?! 훨씬 깔끔하네 이 방법이. 수정해서 다시 commit 올릴게~ 땡큐!

2022-02-19 00:56 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
user_to 는 알림이 가는 user 인거고(내 글에 댓글이 달렸다던지, 좋아요를 받았다던지 할 때)
user_by는 어떤 user가 그 알림을 만들었는지 알려주는 거야.

보통 알림 방식이 **( user_by )가 ( user_to )의 (게시글/댓글)에 좋아요를 눌렀습니다.** 이런 방식이니깐.

2022-02-19 00:57 UTC, Ridealist commented on kkanbu/notification/models.py
> +    is_read = models.BooleanField(default=False)
extra_id는 url 생성할 때 필요해서~
알림이 생긴 게시물/댓글 의 pk 값을 받아오려고 만든 필드야.

2022-02-19 00:58 UTC, Ridealist commented on kkanbu/notification/models.py
> +    is_read = models.BooleanField(default=False)
변수명이 좀 부정확한가... object_id 나 object_pk로 바꿀까 변수명을?

2022-02-19 01:07 UTC, Ridealist commented on kkanbu/notification/views.py
> +class NotificationViewSet(ListModelMixin, GenericViewSet):
와 이런게 또 있구나...
먼저 상속받은 것 부터 mro가 적용되는 거니까, Viewset을 먼저 상속해주고 그 뒤에 Mixin을 쓰는 게 맞는거네.
이렇게 또 배웁니다.ㅎㅎ

2022-02-19 04:10 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
그거는 그냥 메세지로 처리하는게 좋지 않을까 싶은데
noti의 대상이 되는 user만 기록하고, 어떤 noti인지 message or contents로 그 안에 '( user_by )가 ( user_to )의 (게시글/댓글)에 좋아요를 눌렀습니다.' 이게 들어가는거지

2022-02-19 04:12 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    is_read = models.BooleanField(default=False)
알림이 생긴 게시물의 pk는 왜 필요해? url은 만들어서 url필드에 저장하면 되지않아? 그러고 나서는 쓸 일이 없을것같은데

2022-02-19 04:14 UTC, teacherSsamko reviewed
👍

2022-02-19 09:46 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
내 예시가 좀 안좋았던듯. 맞어 사실 알림은 메세지로 처리하면 되지.
근데 태상쌤이 알림을 만든 사람(user_by)의 nickname과 사진을 요청 데이터 목록어 넣어놨더라고.
그래서 noti의 대상이 되는 유저 + noti를 만든 유저 이렇게 2개 값을 저장해야 겠다 생각했어~

2022-02-19 10:06 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
![image](https://user-images.githubusercontent.com/89024993/154796457-75ebc226-ddec-410e-8dc7-b50c80e28e9d.png)

2022-02-19 10:30 UTC, Ridealist commented on kkanbu/notification/models.py
> +    is_read = models.BooleanField(default=False)
이건 형 얘기 듣고 보니 그렇네. url 생성할 때 활용되고서 더 쓰이지 않으면 굳이 저장할 필욘 없겠네.
DB만 잡아먹는 거니 삭제할게~

2022-02-19 11:06 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
형~ review 둘 다 Model 수정하는 거니까, migration 파일 덜 생성되게 이거까지 형 의견 듣고 최종 commit 올릴게~
@teacherSsamko

2022-02-20 02:42 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
우리가 공지사항 같은걸 할 수도 있고 noti에 꼭 user2user가 아니어도 넣을 수 있게 하려면 user를 알릴 사람만 넣으면 될 것 같아. 알림을 만드는 주체는 backend가 되어야하지 user가 되면 그건 알림보다는 그냥 채팅이나 메세지라고 봐야하지 않을까? `알림을 만든 사람`이라고 태상쌤이 말한게 A가 회원님의 글에 좋아요를 눌렀습니다. 의 A를 말하는 거라면 이것역시 message에 넣거나 해야할것 같아. 채팅이나 메세지가 아닌 notification에 from to 를 넣는 건 어색한거같아

2022-02-20 02:45 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
review request는 수정사항이 있거나 토론이 해결되거나 했을때만 요청하면 돼~ ㅋㅋ 그냥 이런 토론같은경우는 댓글로만 진행해도 되니까 매번 review request하지는 말구~

2022-02-20 03:38 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
아 드디어 이해했다...
notification은 사이트(backend)에서 사용자에게 보내는 모든 알림을 포괄하는 개념으로 얘기한거구나!
이 입장에서 보면 확실히 user-by가 있는게 이상하네. 이건 사용자끼리 보내는 내용으로 처리해 message라는 다른 모델을 만들어야 하는 문제인 거고.
그럼 message라는 별도 모델을 만들어서 거기에 이 notification을 ForeignKey로 등록하는게 맞겠네.

2022-02-20 03:41 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
응 앞으로 review request는 논의가 끝나고 commit까지 완료됐을 때 보낼게~~ 미안 자꾸 request 날려서ㅋㅋㅋㅠㅠ

2022-02-20 09:22 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
message라는 별도의 모델을 만들필요가 있을까 싶은데.. 그냥 내용만 들어가는거잖아? 
user 이미지를 보내주는게 필요하면 따로 notification_image라던지 그냥 image라던지 별도의 속성만 만드는게 어때?
그 속성은 비어있을 수도 있는거고 우리가 공지를 할 때, 공지 성격에 따라서 유저이미지랑 관계없이 우리가 원하는 이미지로 알림을 보낼 수도 있도록

2022-02-20 12:44 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
응 notification_image를 만드는 것도 방법이긴 할텐데, 사실 내가 생각한 제일 간단한 방법은 좋아요나 댓글을 단 User 인스턴스를 통해서 profile 이미지를 갖고 오는 것을 생각한 거여서.

음... 뭔가 내 생각에 형이랑 내가 이해하고 있는 notification이 다른 것 같아ㅠㅠ

형 일단 내가 이해하는 것과 형이 이해한게 같은지 부터 한번 확인해볼게~

2022-02-20 12:45 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
![image](https://user-images.githubusercontent.com/89024993/154843114-9e06e5b8-4cdc-4dbc-8fd5-ea3412d9e922.png)

2022-02-20 12:48 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
인디스쿨 기준으로 이게 Notifications '알림' 기능인데, 사실 알림이란건 내 게시글이나 내 댓글에 반응이 있을 때 그걸 알려주는 기능이잖아? 그래서 어떤 유저가 해당 반응을 만들었는지 알림을 만든 사람(닉네임, 사진)이 필요한 거겠고. 나는 이걸 user_by라는 필드를 통해 받으려고 했던거고~

2022-02-20 12:52 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
그래서 만약 notification을 **공지**로 생각해서 더 큰 범위로 '사이트에서 유저에게 제공하는 모든 전달사항'이라고 한다면, notificatino모델 외에 저런 개별 알림을 만든 사람에 대한 정보를 넣을 message 모델을 따로 만들어야 되나 생각 했던거였어.

2022-02-20 12:53 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
나는 나중에 관심있는 주제에 새 글이 등록되었다는 알림 같은 것도 가지 않을까 생각했어.
`'두근두근'게시판에 새 글이 등록되었습니다.`
아니면 인스타그램처럼
`준보, 회택, 태상님께서 회원님의 글에 좋아요를 표시했습니다` 이렇게 여러 개의 좋아요를 묶어서 표시한다던지 하는 알림

2022-02-20 12:54 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
이런 경우에 user_by가 있으면 알림을 주기가 애매하지 않을까

2022-02-20 12:56 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
인디스쿨도 훌륭한 서비스지만 기왕 레퍼런스로 삼을거면 좀 더 커다란 SNS를 레퍼런스로 삼는게 좋지 않을까? 인스타나 블라인드나 페이스북 같은 SNS들의 알림 서비스들

2022-02-20 13:12 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
1. notification - 사이트가 내게 알려주는 모든 전달 사항(공지사항, 신고 사항, 알림 등등 포괄)
- fields : notification_type / user_to / is_read / url / created / modified
2. message - 내 게시물, 내 댓글에 다른 사용자로부터 어떤 action이 있을 때 알림 사항(알림 만)
- fields : notification(ForeignKey) / user_by / created / modified

이렇게 정리를 한거지.

2022-02-20 15:40 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
형... 나 형의 깊은 뜻을 드디어 이해했어...!
확장성을 생각해보면 이게 그렇게 간단히 생각할 문제가 아니네...
좀 더 공부해보고 수정해야겠다. 다른 앱들의 notification DB schema들도 찾아보고.
그다음 다시 Review Request 보낼게. 고마워 형ㅎㅎ 굳 밤 보내!

2022-02-21 07:26 UTC, Ridealist commented on kkanbu/notification/models.py
> +    user_by = models.ForeignKey(
좀 설명할게 많아서 일단 디스코드에 먼저 올렸어.
디스코드-backend 채널에 올린거 피드백 부탁할게 형~~

2022-03-01 18:16 UTC, Ridealist commented
맨 위 PR Description에 최근 수정 사항 적어놓았습니다~!

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
여기가 어떻게 디자인된건지 설명이 좀 필요할거같아~ 각각이 의미하는게 뭔지 왜 GenericForeignKey를 사용했는지~

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    def timesince(self, now=None):
이건 어떻게 사용해? notification.created.timesince 이렇게 하면 돼??

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
url을 사용할때는 reverse나 resolve_url를 사용하는게 좋은데 이것도 그렇게 바꾸는게 좋을것같아
하드코딩해놓으면 나중에 주소 다른데서 바뀐거 모르고 여기는 수정을 못해줘서 에러가 날 수 있거든

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
이건
```python
notify = Notification(message=str(message), **kwargs)
```
이렇게 바꿔주면 될거같아 noti_type만 notification_type으로 받는걸로 변경해서
그런데 message로 string이 아닌 다른게 들어올 수도 있어?

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +from .signals import notify
이거는 `from .signals import notify as notify_signal` 이런식으로 별칭붙여서 사용하는게 본문 코드에서 보기 좋을것같아

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/signals.py
> +notify = Signal()
signal에서 그냥 이것만해주는거야? notification create될때 작업해주는거 없이?

2022-03-07 08:09 UTC, teacherSsamko commented on kkanbu/notification/views.py
> +            "http://127.0.0.1:8000" + instance.get_absolute_url()
이거 이후에 서비스 url로 변경해주어야하니까 위에 `# TODO: replace it with service host` 이런식으로 TODO남겨주자
TODO태그 사용하면 배포전에 TODO 검색해서 할 일이 더 없는지 확인할 수 있어

2022-03-09 14:57 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
맞어 나도 이부분이 가장 큰 변화라 생각했어서 추가 설명이 필요할 것 같았어~~

2022-03-09 14:59 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
일단 알림이 생성 됐다는게 어떤 행위가 발생했다는 거잖아? 그것을 sender라는 용어로 정의한 거야.
예를 들어 댓글이 달렸다거나 좋아요를 받았다거나 추천 게시물을 알려준다거나 하는 것들이지

2022-03-09 15:00 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
근데 이 행위들은 어떤 모델에서든지 발생할 수 있잖아? 위 예시에서는 Comment / PostLike / Post 같은 Model에 instance가 생성되는 것들이겠지? 그래서 이 다양한 모델들을 다 커버하는 ForeignKey를 위해서 GenericForeingKey를 설정해봤어.

2022-03-09 15:03 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
GenericForeingKey로 행위가 발생한 대상들 즉 'sender'들을 DB에 저장하는 이유는 댓글이 달렸으면 댓글 내용을 알림사항에 넣을 수 있고, 좋아요를 받았으면 좋아요를 누른 사용자 nickname을 알려줄 수 있고, 게시물을 추천한다면 게시물 제목을 알림사항에 넣을 수 있고 등등 _**해당 대상의 정보를 가져올 필요**_가 있다고 판단해서 그랬어~

2022-03-09 15:04 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
결국 sender 즉 알림을 만든 대상을 모델과 관계없이 저장하려고 GenericForeingKey를 설정하고, 이것을 받아오기 위한 값으로 sender_content_type과 sender_object_id를 저장해 놓는 거고. 이 두가지 정보를 통해서 sender 정보를 가져올 수 있는거니까.

2022-03-09 15:20 UTC, Ridealist commented on kkanbu/notification/models.py
> +    def timesince(self, now=None):
아 이건 __str__ 메소드 정의할 때 쓰려고 같이 정의해 놓은건데
admin을 수정하면서 __str__ 메소드가 필요없어 보여서 지웠거든.
근데 이것는 그냥 놔둬서 덩그러니 남겨졌네;;

2022-03-09 15:21 UTC, Ridealist commented on kkanbu/notification/models.py
> +    def timesince(self, now=None):
그래도 shell에서 조작할 때나 ORM 조작할 때 __str__ 메소드를 정의해놓는게 더 편하니까
이거 사용해서 __str__ 메소드를 다시 원래대로 추가해놓을게~

2022-03-09 15:22 UTC, Ridealist commented on kkanbu/notification/models.py
> +    def timesince(self, now=None):
이걸 정의한 이유는 해당 notification이 언제 생성되었는지 기준 일자(ex. 5시간전, 2일 전 등등)를 알려주는게
Notification model 객체를 다루는데 더 편할거라 판단해서 그렇게 했었어~

2022-03-09 16:08 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
아니 string이 아닌 다른게 들어올 일은 없어보이긴 하는데(^^;;) 그래도 혹 error 가능성을 대비해 일단 추가해 놓은거야~~

2022-03-09 16:09 UTC, Ridealist commented on kkanbu/notification/models.py
> +from .signals import notify
넵 반영하겠습니다~!

2022-03-09 16:19 UTC, Ridealist commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
아 모델 에서 get_absolute_url 을 정의해주는게 항상 좋은건 아니구나~

2022-03-09 16:22 UTC, Ridealist commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
일단 이걸 정의해 놓은게 GenericForeingKey로 알림을 만든 객체를 DB에 저장해 놓았으니
url 필드를 정의할 필요는 없어보여서 삭제하면서, 이걸 대체할 방법을 고민하다가 추가한 거였거든.
url을 모델 내 메서드로 정의하는 방법으로.

2022-03-09 16:22 UTC, Ridealist commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
그럼 아예 이 부분은 삭제하는게 나을까~?

2022-03-09 16:40 UTC, Ridealist commented on kkanbu/notification/views.py
> +            "http://127.0.0.1:8000" + instance.get_absolute_url()
오 이런 방법이 있었네. 수정 하겠습니다!

2022-03-09 16:45 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
이 부분이 밑에 형이 물어본 부분과 연결돼 있는데,
일단 내가 참고한 notification app은 notification이 create 될 때 작업을 다 model에서 마무리하더라구.

2022-03-09 16:48 UTC, Ridealist commented on kkanbu/notification/signals.py
> +notify = Signal()
응 여기서 따로 추가해주지 않아도 models.py에서 notify_handler 정의해주니까
views.py 파일에서는 notify.send(     ) 이런 식으로 쓰면 notification 객체가 생성되더라고

2022-03-09 16:48 UTC, Ridealist commented on kkanbu/notification/signals.py
> +notify = Signal()
![image](https://user-images.githubusercontent.com/89024993/157489773-93357999-badc-40ee-b19d-9f9fbece8c3e.png)

2022-03-09 16:49 UTC, Ridealist commented on kkanbu/notification/signals.py
> +notify = Signal()
(위에 사진은 내가 개인 repo에서 구현해본 내용)

2022-03-09 16:58 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
notify_handler를 통해서 받은 값들을  Notification 모델 instance에 저장하는 방식이라 일일이 연결해주지 않으면 인식이 안되는 것 같더라구?

2022-03-09 17:00 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
또 형이 얘기해준대로 수정해서 commit 했더니 pre-commit에서 변수를 사용 안했다고 오류 메세지도 뜨네ㅠㅠ

2022-03-09 17:01 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
![image](https://user-images.githubusercontent.com/89024993/157492237-416d0ffd-e009-43eb-8778-fa4a2ed01e99.png)

2022-03-12 07:05 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
오... 그런게 가능하구나 몰랐어 이건 👍

2022-03-12 07:08 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +    )
내가 한 것처럼 하면 58~60 line이 필요없어지거든 그런데 지우지 않고 그대로 둬서 오류가 나는거지~

2022-03-12 07:16 UTC, teacherSsamko requested changes
GenericForeignKey는 사용안해봤는데 덕분에 한번 공부해봐야겠다 ㅋㅋ 다른 수정사항만 반영부탁해~

2022-03-12 07:16 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
아니 get_absolute_url은 그대로 두되, return에 하드코딩하지말고, `return reverse('comment:detail', args=[self.sender.comment.pk])` 이런식으로 return만 수정해주면 될것같아 저 코드는 그냥 생각난대로 쓴거라서 복붙하면 안되고 좀 수정해야할거야~

2022-03-16 13:47 UTC, Ridealist commented
어으... 며칠만의 코딩인지ㅠㅠ 리뷰 늦어서 죄송합니다... 형 얘기해준거 해결한다음 커밋 올릴게~

2022-03-16 13:48 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
형이 조언해준 대로 다른 사람이 코딩해 놓은거 보는게 진짜 공부 많이 되더라...!

2022-03-16 14:34 UTC, Ridealist commented on kkanbu/notification/models.py
> +    )
그렇구나... 생각해보면 단순한건데 좀 어이없는 질문이었다... 수정해서 커밋할게!

2022-03-16 15:12 UTC, Ridealist commented on kkanbu/notification/models.py
> +            return "/api/v1/comment/%d/" % self.sender.comment.pk
응 이해했어! 난 Viewsets으로 정의된 거라 reverse 사용할 수 있으려나 생각했는데 역시 없는 방법은 없구나... 구글링해서 찾은거 반영해서 커밋할게~

2022-03-16 15:21 UTC, Ridealist commented on kkanbu/notification/signals.py
> +notify = Signal()
![image](https://user-images.githubusercontent.com/89024993/158625400-ffeea5a7-d749-4ca2-a0f2-74a53fb44c64.png)

2022-03-16 15:22 UTC, Ridealist commented on kkanbu/notification/signals.py
> +notify = Signal()
PostBlameViewSet에서 작동 잘 되는거 확인했습니다.

2022-03-16 15:29 UTC, Ridealist commented
이거 CI가 제대로 작동 안하는것 같은데 뭐지?? Linter랑 PyTest 돌아가야 되는데 안돌아가네??
actions/checkout 패키지가 2에서 3으로 주 version 업그레이드 되면서 뭔가 문제가 생겼나?!

2022-03-18 07:35 UTC, teacherSsamko commented
> 이거 CI가 제대로 작동 안하는것 같은데 뭐지?? Linter랑 PyTest 돌아가야 되는데 안돌아가네?? actions/checkout 패키지가 2에서 3으로 주 version 업그레이드 되면서 뭔가 문제가 생겼나?!

안돼?? 지금 확인해보니까 체크 잘 돌아갔던데??

2022-03-18 07:37 UTC, teacherSsamko commented on kkanbu/notification/models.py
> +from .signals import notify
d2982bd1e

2022-03-18 07:39 UTC, teacherSsamko approved these changes
긴 리뷰였다 ㅋㅋ 고생했어!! 이제 슬슬 배포해보자

2022-03-18 07:42 UTC, merged

2022-03-19 13:02 UTC, Ridealist commented
> > 이거 CI가 제대로 작동 안하는것 같은데 뭐지?? Linter랑 PyTest 돌아가야 되는데 안돌아가네?? actions/checkout 패키지가 2에서 3으로 주 version 업그레이드 되면서 뭔가 문제가 생겼나?!
> 
> 안돼?? 지금 확인해보니까 체크 잘 돌아갔던데??

처음에 commit 올렸을 때 안돌아가져서 적었는데
다음날 확인해보니 잘 돌아갔더라고~~ 그래서 리뷰 접어놨는데 아예 삭제할걸 그랬다 괜히 형 헷갈리게 했네ㅎㅎ;;